// Generated by Blueprint from schema 'library'.
// Inheritance strategy of the source schema: single-table.
//
// Declarations only. Blueprint never writes an operation body and never
// overwrites a file that already holds one.
#pragma once

#include <string>

#include "blueprint/annotations.hpp"

namespace library {

class Author {
    BP_TABLE("authors");
    BP_COLUMN(birth_year, "INTEGER");
    BP_PK(id);
    BP_COLUMN(id, "INTEGER");
    BP_COLUMN(name, "VARCHAR(120)");

public:
    int birth_year;
    int id;
    std::string name;
};

class Catalogue {
    BP_TABLE("catalogues");
    BP_PK(id);
    BP_COLUMN(id, "INTEGER");
    BP_COLUMN(name, "TEXT");
    BP_COLUMN(default_shelf, "INTEGER");
    BP_COLUMN(overflow, "INTEGER");
    BP_COLUMN(curator, "INTEGER");

public:
    int id;
    std::string name;
    int default_shelf;  // foreign key onto shelves(id)
    int overflow;  // foreign key onto shelves(id)
    int curator;  // foreign key onto authors(id)
};

class LibraryItem {
    BP_TABLE("items");
    BP_PK(id);
    BP_COLUMN(id, "INTEGER");
    BP_COLUMN(title, "VARCHAR(200)");
    BP_COLUMN(class_type, "TEXT");
    BP_COLUMN(isbn, "CHAR(13)");
    BP_COLUMN(page_count, "INTEGER");
    BP_COLUMN(issn, "CHAR(9)");
    BP_COLUMN(volume, "INTEGER");
    BP_COLUMN(shelf, "INTEGER");
    BP_COLUMN(author, "INTEGER");

public:
    int id;
    std::string title;
    std::string class_type;
    std::string isbn;
    int page_count;
    std::string issn;
    int volume;
    int shelf;  // foreign key onto shelves(id)
    int author;  // foreign key onto authors(id)
};

class Shelf {
    BP_TABLE("shelves");
    BP_COLUMN(code, "CHAR(8)");
    BP_PK(id);
    BP_COLUMN(id, "INTEGER");

public:
    std::string code;
    int id;
};

} // namespace library

