-- generated by Blueprint from model 'library'
-- inheritance strategy: table-per-concrete

-- class: library::Author
CREATE TABLE authors (
  birth_year INTEGER,
  id INTEGER NOT NULL,
  name VARCHAR(120),
  PRIMARY KEY (id)
);

-- class: library::Catalogue
CREATE TABLE catalogues (
  id INTEGER NOT NULL,
  name TEXT,
  default_shelf_id INTEGER, -- attribute: default_shelf
  overflow_id INTEGER, -- attribute: overflow
  curator_id INTEGER NOT NULL, -- attribute: curator
  PRIMARY KEY (id),
  FOREIGN KEY (default_shelf_id) REFERENCES shelves(id),
  FOREIGN KEY (overflow_id) REFERENCES shelves(id),
  FOREIGN KEY (curator_id) REFERENCES authors(id)
);

-- class: library::LibraryItem
CREATE TABLE items (
  id INTEGER NOT NULL,
  title VARCHAR(200),
  class_type TEXT NOT NULL,
  isbn CHAR(13),
  page_count INTEGER,
  issn CHAR(9),
  volume INTEGER,
  shelf_id INTEGER, -- attribute: shelf
  author_id INTEGER NOT NULL, -- attribute: author
  PRIMARY KEY (id),
  FOREIGN KEY (shelf_id) REFERENCES shelves(id),
  FOREIGN KEY (author_id) REFERENCES authors(id)
);

-- class: library::Shelf
CREATE TABLE shelves (
  code CHAR(8),
  id INTEGER NOT NULL,
  PRIMARY KEY (id)
);

-- class: library::Catalogue (join)
CREATE TABLE catalogues_items (
  catalogue_id INTEGER NOT NULL,
  items_id INTEGER NOT NULL,
  FOREIGN KEY (catalogue_id) REFERENCES catalogues(id),
  FOREIGN KEY (items_id) REFERENCES items(id)
);

