#!/usr/bin/env python3
"""Generates translation units of a chosen size for the scaling measurement.

Not part of the build. The tool builds and runs from a C++20 compiler and
CMake alone; this exists only so that extraction cost can be measured against
translation unit size on more than the two real inputs the repository ships.

Every generated class carries one of each member shape the reader has to tell
apart, so what is timed is real work and not a file full of empty classes.
All of them relate to the same root class, which keeps object sizes constant:
a chain of classes each holding the previous one by value doubles in size at
every step and the front end rejects it long before the interesting sizes.

    python tools/gen_scaling_input.py 100 build/scaling/n100.hpp
"""
import os
import sys

TEMPLATE = """// generated by tools/gen_scaling_input.py, {count} classes
#pragma once

#include <memory>
#include <string>
#include <vector>

namespace scaling {{

{bodies}}}  // namespace scaling
"""

ROOT = """class Node0 {
public:
    virtual ~Node0();
    virtual double weight() const;

    int id;
    std::string label;
};

"""

CLASS = """class Node{i} : public Node0 {{
public:
    ~Node{i}() override;
    double weight() const override;
    void attach(const Node0& other);

    int index_{i};
    std::string name_{i};

private:
    Node0 owned_{i};
    Node0* borrowed_{i};
    std::unique_ptr<Node0> exclusive_{i};
    std::shared_ptr<Node0> shared_{i};
    std::vector<Node0> many_{i};
}};

"""


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    count = int(sys.argv[1])
    path = sys.argv[2]
    bodies = [ROOT]
    for i in range(1, count):
        bodies.append(CLASS.format(i=i))
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write(TEMPLATE.format(count=count, bodies="".join(bodies)))
    print("wrote {0} with {1} classes".format(path, count))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
