#include "blueprint/emit.hpp"

#include <algorithm>
#include <memory>
#include <sstream>

namespace bp {

std::string to_string(Notation n) { return n == Notation::PlantUml ? "plantuml" : "mermaid"; }

Notation notation_from_string(const std::string& s) {
    return s == "mermaid" || s == "mmd" ? Notation::Mermaid : Notation::PlantUml;
}

std::string diagram_alias(const std::string& qualified_name) {
    std::string alias;
    alias.reserve(qualified_name.size());
    for (const char c : qualified_name) {
        const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                        (c >= '0' && c <= '9') || c == '_';
        alias.push_back(ok ? c : '_');
    }
    if (alias.empty() || (alias.front() >= '0' && alias.front() <= '9')) alias.insert(alias.begin(), 'C');
    return alias;
}

namespace {

// Anything the two notations cannot express in their own syntax travels in a
// note. UML notes are the language's own mechanism for annotating an element,
// so this is not a smuggling channel but the intended one.
std::string note_payload(const Classifier& c) {
    std::string payload;
    const auto add = [&payload](const std::string& text) {
        if (!payload.empty()) payload += "; ";
        payload += text;
    };
    if (!c.template_parameters.empty()) {
        std::string params;
        for (std::size_t k = 0; k < c.template_parameters.size(); ++k) {
            if (k) params += ", ";
            params += c.template_parameters[k];
        }
        add("template=" + params);
    }
    for (const auto& t : c.tags) add(t.name + "=" + t.value);
    for (const auto& a : c.attributes) {
        for (const auto& t : a.tags) add(a.name + "." + t.name + "=" + t.value);
    }
    return payload;
}

// The shared traversal. A subclass supplies the syntax; the order of elements
// and the decisions about what is worth emitting live here, once.
class DiagramEmitter {
public:
    virtual ~DiagramEmitter() = default;

    std::string emit(const Model& model) {
        prologue(model);
        for (const auto& c : model.classifiers) {
            open_classifier(c);
            for (const auto& a : c.attributes) attribute(a);
            for (const auto& op : c.operations) operation(op);
            close_classifier(c);
            const std::string payload = note_payload(c);
            if (!payload.empty()) note(c, payload);
        }
        for (const auto& r : model.relations) relation(r);
        epilogue();
        return out_.str();
    }

protected:
    virtual void prologue(const Model& model) = 0;
    virtual void open_classifier(const Classifier& c) = 0;
    virtual void attribute(const Attribute& a) = 0;
    virtual void operation(const Operation& op) = 0;
    virtual void close_classifier(const Classifier& c) = 0;
    virtual void note(const Classifier& c, const std::string& payload) = 0;
    virtual void relation(const Relation& r) = 0;
    virtual void epilogue() = 0;

    static char visibility_symbol(Visibility v) {
        switch (v) {
        case Visibility::Public: return '+';
        case Visibility::Protected: return '#';
        case Visibility::Private: return '-';
        case Visibility::Package: return '~';
        }
        return '+';
    }

    std::ostringstream out_;
};

// ---------------------------------------------------------------------------
// PlantUML
// ---------------------------------------------------------------------------
class PlantUmlEmitter final : public DiagramEmitter {
protected:
    void prologue(const Model& model) override {
        out_ << "@startuml\n";
        out_ << "' generated by Blueprint\n";
        out_ << "title " << model.name << "\n";
        out_ << "skinparam classAttributeIconSize 0\n\n";
    }

    void open_classifier(const Classifier& c) override {
        switch (c.kind) {
        case ClassifierKind::Interface: out_ << "interface "; break;
        case ClassifierKind::Enumeration: out_ << "enum "; break;
        default:
            if (c.is_abstract) out_ << "abstract ";
            out_ << "class ";
        }
        out_ << "\"" << c.qualified_name << "\" as " << diagram_alias(c.qualified_name);
        if (c.kind == ClassifierKind::Struct) out_ << " <<struct>>";
        if (c.kind == ClassifierKind::Template) out_ << " <<template>>";
        for (const auto& s : c.stereotypes) out_ << " <<" << s << ">>";
        out_ << " {\n";
        for (const auto& e : c.enumerators) out_ << "  " << e << "\n";
    }

    void attribute(const Attribute& a) override {
        out_ << "  " << visibility_symbol(a.visibility) << " ";
        if (a.scope == Scope::Classifier) out_ << "{static} ";
        out_ << a.name << " : " << a.type;
        if (a.multiplicity != "1" && !a.multiplicity.empty()) out_ << " [" << a.multiplicity << "]";
        out_ << "\n";
    }

    void operation(const Operation& op) override {
        out_ << "  " << visibility_symbol(op.visibility) << " ";
        if (op.scope == Scope::Classifier) out_ << "{static} ";
        if (op.is_pure) out_ << "{abstract} ";
        else if (op.is_virtual) out_ << "{virtual} ";
        out_ << op.name << "(";
        for (std::size_t k = 0; k < op.parameters.size(); ++k) {
            if (k) out_ << ", ";
            // A parameter with no name is common in a declaration and must
            // not be written as ": type", which reads back as a type called
            // ": type" and silently breaks the round trip.
            if (!op.parameters[k].name.empty()) out_ << op.parameters[k].name << " : ";
            out_ << op.parameters[k].type;
        }
        out_ << ")";
        if (op.is_const) out_ << " const";
        if (!op.return_type.empty()) out_ << " : " << op.return_type;
        out_ << "\n";
    }

    void close_classifier(const Classifier&) override { out_ << "}\n\n"; }

    void note(const Classifier& c, const std::string& payload) override {
        out_ << "note top of " << diagram_alias(c.qualified_name) << " : bp: " << payload << "\n\n";
    }

    void relation(const Relation& r) override {
        const std::string from = diagram_alias(r.from);
        const std::string to = diagram_alias(r.to);
        switch (r.kind) {
        case RelationKind::Generalization:
            out_ << to << " <|-- " << from;
            if (r.is_virtual_base || r.visibility != Visibility::Public) {
                out_ << " : " << (r.is_virtual_base ? "virtual " : "") << to_string(r.visibility);
            }
            out_ << "\n";
            return;
        case RelationKind::Realization: out_ << to << " <|.. " << from << "\n"; return;
        case RelationKind::Dependency: out_ << from << " ..> " << to << "\n"; return;
        case RelationKind::Composition: out_ << from << " *--"; break;
        case RelationKind::Aggregation: out_ << from << " o--"; break;
        case RelationKind::Association: out_ << from << " -->"; break;
        }
        if (!r.multiplicity.empty()) out_ << " \"" << r.multiplicity << "\"";
        out_ << " " << to;
        if (!r.label.empty()) out_ << " : " << r.label;
        out_ << "\n";
    }

    void epilogue() override { out_ << "@enduml\n"; }
};

// ---------------------------------------------------------------------------
// Mermaid
// ---------------------------------------------------------------------------
class MermaidEmitter final : public DiagramEmitter {
protected:
    // Mermaid reads angle brackets as its own generic delimiters and uses
    // tildes instead, so every type spelling has to be translated on the way
    // out. This is the concrete cost of supporting a second notation.
    static std::string type_text(std::string t) {
        std::replace(t.begin(), t.end(), '<', '~');
        std::replace(t.begin(), t.end(), '>', '~');
        return t;
    }

    void prologue(const Model& model) override {
        out_ << "%% generated by Blueprint\n";
        out_ << "classDiagram\n";
        out_ << "  %% title: " << model.name << "\n";
        out_ << "  direction LR\n";
    }

    void open_classifier(const Classifier& c) override {
        out_ << "  class " << diagram_alias(c.qualified_name) << "[\"" << c.qualified_name
             << "\"] {\n";
        if (c.kind == ClassifierKind::Interface) out_ << "    <<interface>>\n";
        if (c.kind == ClassifierKind::Enumeration) out_ << "    <<enumeration>>\n";
        if (c.kind == ClassifierKind::Struct) out_ << "    <<struct>>\n";
        if (c.kind == ClassifierKind::Template) out_ << "    <<template>>\n";
        if (c.is_abstract) out_ << "    <<abstract>>\n";
        for (const auto& s : c.stereotypes) out_ << "    <<" << s << ">>\n";
        for (const auto& e : c.enumerators) out_ << "    " << e << "\n";
    }

    void attribute(const Attribute& a) override {
        out_ << "    " << visibility_symbol(a.visibility) << type_text(a.type) << " " << a.name;
        if (a.scope == Scope::Classifier) out_ << "$";
        if (a.multiplicity != "1" && !a.multiplicity.empty()) out_ << " [" << a.multiplicity << "]";
        out_ << "\n";
    }

    void operation(const Operation& op) override {
        out_ << "    " << visibility_symbol(op.visibility) << op.name << "(";
        for (std::size_t k = 0; k < op.parameters.size(); ++k) {
            if (k) out_ << ", ";
            out_ << type_text(op.parameters[k].type);
            if (!op.parameters[k].name.empty()) out_ << " " << op.parameters[k].name;
        }
        out_ << ")";
        if (op.is_pure) out_ << "*";
        else if (op.scope == Scope::Classifier) out_ << "$";
        if (op.is_const) out_ << " const";
        if (!op.return_type.empty()) out_ << " " << type_text(op.return_type);
        out_ << "\n";
    }

    void close_classifier(const Classifier&) override { out_ << "  }\n"; }

    void note(const Classifier& c, const std::string& payload) override {
        out_ << "  note for " << diagram_alias(c.qualified_name) << " \"bp: " << payload << "\"\n";
    }

    void relation(const Relation& r) override {
        const std::string from = diagram_alias(r.from);
        const std::string to = diagram_alias(r.to);
        switch (r.kind) {
        case RelationKind::Generalization:
            out_ << "  " << to << " <|-- " << from;
            if (r.is_virtual_base || r.visibility != Visibility::Public) {
                out_ << " : " << (r.is_virtual_base ? "virtual " : "") << to_string(r.visibility);
            }
            out_ << "\n";
            return;
        case RelationKind::Realization: out_ << "  " << to << " <|.. " << from << "\n"; return;
        case RelationKind::Dependency: out_ << "  " << from << " ..> " << to << "\n"; return;
        case RelationKind::Composition: out_ << "  " << from << " *--"; break;
        case RelationKind::Aggregation: out_ << "  " << from << " o--"; break;
        case RelationKind::Association: out_ << "  " << from << " -->"; break;
        }
        if (!r.multiplicity.empty()) out_ << " \"" << r.multiplicity << "\"";
        out_ << " " << to;
        if (!r.label.empty()) out_ << " : " << r.label;
        out_ << "\n";
    }

    void epilogue() override {}
};

} // namespace

std::string emit_class_diagram(const Model& model, Notation notation) {
    if (notation == Notation::Mermaid) return MermaidEmitter().emit(model);
    return PlantUmlEmitter().emit(model);
}

} // namespace bp
