# The measurements of the report, reproduced with one command:
#     cmake --build build --target measure
#
# Every number in the results chapter comes from here. Nothing in the report
# is a figure that this target cannot produce again on the same machine.

if(NOT DEFINED BLUEPRINT_EXE)
    message(FATAL_ERROR "BLUEPRINT_EXE is not set; run this through the measure target")
endif()

find_program(CLANG_EXE NAMES clang++ clang++.exe)
if(NOT CLANG_EXE)
    message(FATAL_ERROR "clang++ was not found on PATH; extraction cannot be timed without it")
endif()

set(COMMON --clang "${CLANG_EXE}" --stdstub "${SOURCE_DIR}/stdstub" -I "${SOURCE_DIR}/include")
set(SCALING "${BINARY_DIR}/scaling")

message(STATUS "")
message(STATUS "=== Machine")
execute_process(COMMAND "${CLANG_EXE}" --version OUTPUT_VARIABLE clang_version)
string(REGEX MATCH "[^\n]+" clang_first "${clang_version}")
cmake_host_system_information(RESULT os_name QUERY OS_NAME)
cmake_host_system_information(RESULT os_release QUERY OS_RELEASE)
cmake_host_system_information(RESULT cpus QUERY NUMBER_OF_LOGICAL_CORES)
cmake_host_system_information(RESULT cpu QUERY PROCESSOR_DESCRIPTION)
message(STATUS "  system      ${os_name} ${os_release}")
message(STATUS "  processor   ${cpu}, ${cpus} logical cores")
message(STATUS "  build       ${BUILD_COMPILER}")
message(STATUS "  front end   ${clang_first}")
message(STATUS "  cmake       ${CMAKE_VERSION}")

message(STATUS "")
message(STATUS "=== Extraction cost against translation unit size")
find_package(Python3 COMPONENTS Interpreter QUIET)
if(Python3_Interpreter_FOUND)
    set(inputs)
    foreach(n 10 25 50 100 200 400 800)
        execute_process(COMMAND "${Python3_EXECUTABLE}"
                                "${SOURCE_DIR}/tools/gen_scaling_input.py" ${n}
                                "${SCALING}/n${n}.hpp"
                        OUTPUT_QUIET)
        list(APPEND inputs "${SCALING}/n${n}.hpp")
    endforeach()
    execute_process(COMMAND "${BLUEPRINT_EXE}" bench ${inputs} ${COMMON}
                            --root "${SCALING}" --repeat 3)
else()
    message(STATUS "  skipped: the scaling inputs are generated by a Python script and "
                   "no interpreter was found. The two real inputs below are still measured.")
endif()

message(STATUS "")
message(STATUS "=== The two real inputs")
execute_process(COMMAND "${BLUEPRINT_EXE}" bench "${SOURCE_DIR}/examples/library.hpp" ${COMMON}
                        --root "${SOURCE_DIR}/examples" --repeat 3)
execute_process(COMMAND "${BLUEPRINT_EXE}" bench "${SOURCE_DIR}/examples/self.hpp" ${COMMON}
                        --root "${SOURCE_DIR}/include" --repeat 3)

message(STATUS "")
message(STATUS "=== Round trip fidelity")
execute_process(COMMAND "${BLUEPRINT_EXE}" roundtrip "${SOURCE_DIR}/examples/library.hpp" ${COMMON}
                        --root "${SOURCE_DIR}/examples" --name library)
execute_process(COMMAND "${BLUEPRINT_EXE}" roundtrip "${SOURCE_DIR}/examples/self.hpp" ${COMMON}
                        --root "${SOURCE_DIR}/include" --name blueprint)
